#Base/migration/0005_review_createdat.py

# Generated by Django 3.1.4 on 2021-01-22 00:06

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210119_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
